ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/common
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
